# Run conf
LINKS_TO_IMAGE=mysql
VOLUMES_FROM_IMAGE="magento media"
RUN_OPTS="-di --link ${LINKS_TO_IMAGE}_${ENV_MODE}:db -p 8080:80"
SINGLETON=1

# Mode conf
DEV_MODE_OPTS="-e REMOTE_IP=$(what_is_my_ip)"
